---
plugin: amazon.aws.aws_ec2
profile: default
regions:
  - eu-central-1
filters:
  instance-state-name : running
keyed_groups:
  - prefix: env
    key: tags['env']
  - prefix: dev
    key: tags['ssm']